Rename all scripts in subsection "Terminal" of section "Application management"

diff --git a/scripts/application_management-modules/terminal/execcmdinterm b/scripts/application_management-modules/terminal/execcmdinterm
--- a/scripts/application_management-modules/terminal/execcmdinterm
+++ b/scripts/application_management-modules/terminal/execcmdinterm
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 # 
 # File:
-#   execlasttermcommand
+#   execcmdinterm
 # 
 # Description:
-#   Execute the last command of a terminal emulator.
+#   Execute a command in a terminal emulator.
 # 
 # Usage:
-#   execlasttermcommand (--class <TERM_CLASS> | --title <TERM_TITLE>) [options]
-#           -- <command>
+#   execcmdinterm (--class <TERM_CLASS> | --title <TERM_TITLE>) [options] --
+#           <command>
 # 
 # Options:
 #   -c --class <TERM_CLASS>    class of the terminal emulator (required if
@@ -31,9 +31,6 @@
 # Notes:
 #   This utility should be used with a keybinding or in a script.
 # 
-#   If the last command in the terminal emulator is  moved to but not executed,
-#   increase the usleep time in the xte command.
-# 
 
 # ======= CONFIGURATIONS ==============
 
@@ -42,16 +39,16 @@
 # may focused too quickly, causing none or only a part of the events to succeed.
 # (Note: This delay time is also applied before refocusing the previously
 # focused window).
-readonly XEVENTS_DELAY_TIME='.18'
+readonly XEVENTS_DELAY_TIME='.15'
 
 # ======= ! CONFIGURATIONS ==============
 
-OPTS="$(getopt -q -o c:,t:,r --long class:,title:,refocus -n \
-    'execlasttermcommand' -- "${@}")"
+OPTS="$(getopt -q -o c:,t:,r --long class:,title:,refocus -n 'execcmdinterm' \
+    -- "${@}")"
 if [ "$?" -ne 0 ]; then
   # output errors as a desktop notification since this script is meant to be
   # used with a keybinding and errors printed to stderr will not be seen.
-  notify-send 'execlasttermcommand (err): unrecognized option'
+  notify-send 'execcmdinterm (err): unrecognized option'
   exit 1
 fi
 eval set -- "${OPTS}"
@@ -68,7 +65,13 @@ while true; do
 done
 
 if [ -z "${TERM_CLASS}" ] && [ -z "${TERM_TITLE}" ]; then
-  notify-send 'execlasttermcommand (err): must use option --class or --title'
+  notify-send 'execcmdinterm (err): must use option --class or --title'
+  exit 1
+fi
+
+if [ "$#" -eq 0 ]; then
+  # print to the terminal for testing purposes
+  echo 'execcmdinterm: no execute command provided' 1>&2
   exit 1
 fi
 
@@ -118,11 +121,30 @@ if [ -n "${termWindId}" ]; then
   
   # ---------  xte  ---------
 
-  xte 'usleep 25000' 'key Up' 'key Return'
+  # Note: Xte sometimes fails to completely paste a string with more than 249
+  # characters. As a result, a string with more than 249 characters is pasted
+  # by every 249 character part.
+  argStr="${@}"
+  if [ "${#argStr}" -gt 249 ]; then
+    for ((i=0; i<=${#argStr}; i+=249)); do
+      xte "str ${argStr:${i}:249}"
+    done
+    xte 'key Return'
+  else
+		xte <<-EOF
+			str ${@}
+			usleep 14000
+			key Return
+		EOF
+  fi
 
   # ---------  xdotool  ---------
 
-  # xdotool sleep .007 key Up key Return
+  # xdotool type "${@}"
+  # # must run a separate xdotool command as "type" will type everything after
+  # # it; also a much higher sleep time is needed as xdotool types each
+  # # character (instead of pasting the string).
+  # xdotool sleep .5 key Return
 
   if [ "${OPT_REFOCUS}" = 'true' ]; then
     [ -n "${XEVENTS_DELAY_TIME}" ] && sleep "${XEVENTS_DELAY_TIME}"
