Generify solution names

diff --git a/scripts/gnu-linux-main/file_management/renmrec b/scripts/gnu-linux-main/file_management/renmrec
--- a/scripts/gnu-linux-main/file_management/renmrec
+++ b/scripts/gnu-linux-main/file_management/renmrec
@@ -3,11 +3,11 @@
 # Rename all files matching a name recursively.
 # 
 # Usage:
-#   renrec <old file name> <new file name>
+#   renmrec <old file name> <new file name>
 # 
 
 if [ "$#" -ne 2 ]; then
-  echo 'renrec: invalid number of arguments' 1>&2
+  echo 'renmrec: invalid number of arguments' 1>&2
   exit 1
 fi
 
diff --git a/scripts/gnu-linux-main/shell_management/remlastnbashhistentries b/scripts/gnu-linux-main/shell_management/remlastnbashhistentries
--- a/scripts/gnu-linux-main/shell_management/remlastnbashhistentries
+++ b/scripts/gnu-linux-main/shell_management/remlastnbashhistentries
@@ -1,22 +1,22 @@
 #!/usr/bin/env bash
 # 
-# Remove the last N entries from the bash history.
+# Remove the last N bash history entries.
 # 
 # Usage (script must be sourced for history command to work):
-#   source remlastnhistentries; _remlastnhistentries <1-100>
+#   source remlastnbashhistentries; _remlastnbashhistentries <1-100>
 # 
 # Source:
 #   http://unix.stackexchange.com/a/65076
 # 
 
-_remlastnhistentries() {
+_remlastnbashhistentries() {
   local numCurrHistEntries="$(history | wc -l)"
 
   if [ "$#" -eq 0 ]; then
-    echo -e 'remlastnhistentries: no argument' 1>&2
+    echo -e 'remlastnbashhistentries: no argument' 1>&2
     return 1
   elif [[ ! "${1}" =~ ^[0-9]+$ || "${1}" -lt 1 || "${1}" -gt 100 ]]; then
-    echo -e 'remlastnhistentries: invalid argument; must be a number\n'\
+    echo -e 'remlastnbashhistentries: invalid argument; must be a number\n'\
         ' between 1 and 100 (inclusive)' 1>&2
     return 1
   fi
diff --git a/scripts/mobile-android/utilities/getmobilecontactinfo b/scripts/mobile-android/utilities/getmobilecontactinfo
--- a/scripts/mobile-android/utilities/getmobilecontactinfo
+++ b/scripts/mobile-android/utilities/getmobilecontactinfo
@@ -3,11 +3,11 @@
 # Get contact info from an Android device.
 # 
 # Usage:
-#   contactinfo <contact phone or name>
+#   getmobilecontactinfo <contact phone or name>
 # 
 
 if [ "$#" -eq 0 ]; then
-  echo 'contactinfo: contact phone no. or name required' 1>&2
+  echo 'getmobilecontactinfo: contact phone no. or name required' 1>&2
   exit 1
 fi
 
diff --git a/scripts/mobile-android/utilities/sendsms b/scripts/mobile-android/utilities/sendsms
--- a/scripts/mobile-android/utilities/sendsms
+++ b/scripts/mobile-android/utilities/sendsms
@@ -3,7 +3,7 @@
 # Send an sms using an Android device.
 # 
 # Usage:
-#   sms <phone no.> <message>
+#   sendsms <phone no.> <message>
 # 
 #   message: may contain "\n" for newlines.
 # 
@@ -17,7 +17,7 @@ readonly MSG_SEND_BTN_X_Y='661 1226'
 # ======= ! CONFIGURATIONS ==============
 
 if [ "$#" -lt 2 ]; then
-  echo 'sms: invalid number of arguments' 1>&2
+  echo 'sendsms: invalid number of arguments' 1>&2
   exit 1
 fi
 
diff --git a/scripts/mobile-generic/management/mountmtpdev b/scripts/mobile-generic/management/mountmtpdev
--- a/scripts/mobile-generic/management/mountmtpdev
+++ b/scripts/mobile-generic/management/mountmtpdev
@@ -4,7 +4,7 @@
 # 
 # Usage:
 #   (script must be sourced for cd to work)
-#   source mtp; _mtp <action>
+#   source mountmtpdev; _mountmtpdev <action>
 # 
 #   action:
 #     "mount" or "m" to mount
@@ -19,6 +19,9 @@
 #       sudo groupadd fuse
 #       sudo gpasswd -a "${USER}" fuse
 # 
+# Note:
+#  This has only been tested with Android devices.
+# 
 
 # ======= CONFIGURATIONS ==============
 
@@ -30,9 +33,10 @@ DEV_CD_DIR='Internal storage/DCIM/Camera'
 
 # ======= ! CONFIGURATIONS ==============
 
-_mtp() {
+_mountmtpdev() {
   if [ "$#" -eq 0 ]; then
-    echo 'mtp: no arguments: "mount", "m", "unmount" or "u" required' 1>&2
+    echo 'mountmtpdev: no arguments: "mount", "m", "unmount" or "u" required' \
+        1>&2
     return 1
   fi
 
@@ -57,7 +61,7 @@ _mtp() {
 
       fusermount -u "${MOUNTPOINT_DIR}"
       if [ "$?" -eq 0 ] && ! mount | grep "${MOUNTPOINT_DIR}" >/dev/null; then
-        echo "mtp: device successfully unmounted from ${MOUNTPOINT_DIR}"
+        echo "mountmtpdev: device successfully unmounted from ${MOUNTPOINT_DIR}"
       fi
       ;;
   esac
diff --git a/scripts/utilities-main/general_text_manipulation/replrec b/scripts/utilities-main/general_text_manipulation/replrec
--- a/scripts/utilities-main/general_text_manipulation/replrec
+++ b/scripts/utilities-main/general_text_manipulation/replrec
@@ -8,7 +8,7 @@
 # recursively.
 # 
 # Usage:
-#   reprec <text to replace> <replacement text>
+#   replrec <text to replace> <replacement text>
 # 
 
 # ======= CONFIGURATIONS ==============
@@ -17,15 +17,15 @@
 readonly BACKUP=true
 
 # Directory where backups are stored
-readonly BACKUPS_DIR="${HOME}/.unixfoundation/shell/reprec-backups/"
+readonly BACKUPS_DIR="${HOME}/.unixfoundation/shell/replrec-backups/"
 
 # ======= ! CONFIGURATIONS ==============
 
 if [ "$#" -ne 2 ]; then
-  echo 'reprec: invalid number of arguments' 1>&2
+  echo 'replrec: invalid number of arguments' 1>&2
   exit 1
 elif [ -z "${1}" ]; then
-  echo 'reprec: first argument empty' 1>&2
+  echo 'replrec: first argument empty' 1>&2
   exit 1
 fi
 
diff --git a/scripts/utilities-main/other/runcountdowntimer b/scripts/utilities-main/other/runcountdowntimer
--- a/scripts/utilities-main/other/runcountdowntimer
+++ b/scripts/utilities-main/other/runcountdowntimer
@@ -3,7 +3,7 @@
 # Run a countdown timer in the terminal.
 # 
 # Usage:
-#   countdown <seconds>
+#   runcountdowntimer <seconds>
 # 
 # Source:
 #   https://superuser.com/a/611582
@@ -17,10 +17,10 @@ readonly PRINT_DAYS_ALSO=false
 # ======= ! CONFIGURATIONS ==============
 
 if [ "$#" -eq 0 ]; then
-  echo 'countdown: time required in seconds' 1>&2
+  echo 'runcountdowntimer: time required in seconds' 1>&2
   exit 1
 elif [[ ! "${1}" =~ ^[0-9]+$ ]]; then
-  echo 'countdown: argument must be a number (seconds)' 1>&2
+  echo 'runcountdowntimer: argument must be a number (seconds)' 1>&2
   exit 1
 fi
 
diff --git a/scripts/utilities-modules/general_program_management/retfileforcmd b/scripts/utilities-modules/general_program_management/retfileforcmd
--- a/scripts/utilities-modules/general_program_management/retfileforcmd
+++ b/scripts/utilities-modules/general_program_management/retfileforcmd
@@ -10,13 +10,13 @@
 # 
 # Examples:
 #   # locate a file from a database for gedit
-#   alias geditloc='returnfileforcmd {gedit --new-window} --l'
+#   alias geditloc='retfileforcmd {gedit --new-window} --l'
 # 
 #   # recursively find a file for gedit
-#   alias geditr='returnfileforcmd {gedit --new-window} --r'
+#   alias geditr='retfileforcmd {gedit --new-window} --r'
 # 
 #   # same as previous except allow files only to be returned
-#   alias geditr='returnfileforcmd {gedit --new-window} --r --f'
+#   alias geditr='retfileforcmd {gedit --new-window} --r --f'
 # 
 #   # use the aliases on their own or with other options such as --3 to return
 #   # the third found occurrence or --a to return all occurrences.
@@ -24,7 +24,7 @@
 #   geditr --a config.sh
 # 
 # Usage:
-#   returnfileforcmd {<command to execute>} [options] <partial file name>
+#   retfileforcmd {<command to execute>} [options] <partial file name>
 #         [directory]
 # 
 #   directory: directory to search in; applies only to the recursive search
@@ -82,8 +82,8 @@ for ((x=1; x<=$#; x++)); do
   fi
 done
 if [ -z "${execCmd}" ]; then
-  echo -e  'returnfileforcmd: invalid arguments:\nexecute command not'\
-      'specified' 1>&2
+  echo -e  'retfileforcmd: invalid arguments:\nexecute command not specified' \
+      1>&2
   exit 1
 fi
 
@@ -91,7 +91,7 @@ execCmd="${execCmd#{}"
 execCmd="${execCmd%\}}"
 
 OPTS="$(getopt -q -o '#' --long l,r,f,d,1,2,3,4,5,6,7,8,9,a,e -n \
-    'returnfileforcmd' -- "${@}")"
+    'retfileforcmd' -- "${@}")"
 eval set -- "${OPTS}"
 while true; do
   case "${1}" in
@@ -111,12 +111,12 @@ done
 case "${SEARCH_METHOD}" in
   'locate')
     if [ "$#" -eq 0 ]; then
-      echo 'returnfileforcmd: no file specified' 1>&2
+      echo 'retfileforcmd: no file specified' 1>&2
       exit 1
     fi
     if ! hash ${LOCATE_COMMAND} > /dev/null 2>&1; then
-      echo "returnfileforcmd: command \"${LOCATE_COMMAND}\" does not"\
-          "exist" 1>&2
+      echo "retfileforcmd: command \"${LOCATE_COMMAND}\" does not exist" \
+          1>&2
       exit 1
     fi
 
@@ -133,7 +133,7 @@ case "${SEARCH_METHOD}" in
     output="$(${LOCATE_COMMAND} ${lctOpts} "${@}")"
 
     if [ -z "${output}" ]; then
-      echo 'returnfileforcmd: no files or directories found' 1>&2
+      echo 'retfileforcmd: no files or directories found' 1>&2
     else
       output="$(echo "${output}" | sed 's/ /\\n/g')"
 
@@ -147,7 +147,7 @@ case "${SEARCH_METHOD}" in
 
   'recursively find')
     if [ "$#" -eq 0 ]; then
-      echo 'returnfileforcmd: no file specified' 1>&2
+      echo 'retfileforcmd: no file specified' 1>&2
       exit 1
     elif [ "$#" -ge 2 ]; then
       dir="${2}"
@@ -162,7 +162,7 @@ case "${SEARCH_METHOD}" in
     output="$(find "${dir}" ${optType} -name "*${1}*" 2>/dev/null)"
 
     if [ -z "${output}" ]; then
-      echo 'returnfileforcmd: no files or directories found' 1>&2
+      echo 'retfileforcmd: no files or directories found' 1>&2
     else
       if [ "${ALL_OCCURRENCES}" != 'true' ]; then
         if [ -n "${FIND_OCCURRENCE}" ]; then
