miscellaneous bin/ updates

diff --git a/bin/main-no_output/shell/remlastnhistentries b/bin/main-no_output/shell/remlastnhistentries
--- a/bin/main-no_output/shell/remlastnhistentries
+++ b/bin/main-no_output/shell/remlastnhistentries
@@ -10,18 +10,19 @@
 # 
 
 _remlastnhistentries() {
-  numCurrHistEntries="$(history | wc -l)"
+  local numCurrHistEntries="$(history | wc -l)"
 
   if [ "$#" -eq 0 ]; then
     echo -e 'remlastnhistentries: no argument' 1>&2
     return 1
   elif [[ ! "${1}" =~ ^[0-9]+$ || "${1}" -lt 1 || "${1}" -gt 100 ]]; then
-    echo -e 'remlastnhistentries: invalid argument; see documentation' 1>&2
+    echo -e 'remlastnhistentries: invalid argument; must be a number\n'\
+        ' between 1 and 100 (inclusive)' 1>&2
     return 1
   fi
 
-  count="${1}"
-  start=$((numCurrHistEntries - count))
+  local count="${1}"
+  local start=$((numCurrHistEntries - count))
 
   while [ "${count}" -ge 0 ]; do
     history -d "${start}"
diff --git a/bin/modules/x11/exeprogandwindact b/bin/modules/x11/exeprogandwindact
--- a/bin/modules/x11/exeprogandwindact
+++ b/bin/modules/x11/exeprogandwindact
@@ -4,15 +4,22 @@
 # 
 # Dependencies:
 #   wmctrl (used to determine if the window is already open and get the window
-#     ID of the new window)
+#     ID of and move the new window)
 # 
 # Notes:
+#   This solution relies on the PID of the opened program to get its window ID
+#   or title. The returned PID will sometimes be different than the PID of the
+#   running process. In this case, retrieving the window ID or title will fail.
+# 
 #   If this module is used with a command that uses quotes, the quotes must be
 #   within outer quotes to be interpreted.
-#       E.g.:
-#         <command> --opt="opt_arg"
-#         # would have to be
-#         <command> --opt='"opt_arg"'
+#     Example:
+#       <command> --opt="opt_arg"
+#       # would have to be
+#       <command> --opt='"opt_arg"'
+# 
+#   If the command's arguments contain newlines, the text on each new line will
+#   be interpreted as an individual command.
 # 
 
 # ======= CONFIGURATIONS ==============
@@ -24,11 +31,9 @@ WIND_ACTION() {
       local idOrTitle="${WIND_TITLE}"
 
   # Create custom window action below
-
-  #wmctrl ${iopt} -r "${idOrTitle}" -b remove,maximized_vert,maximized_horz
-  #wmctrl ${iopt} -r "${idOrTitle}" -b remove,maximized_vert,maximized_horz
-  #wmctrl ${iopt} -r "${idOrTitle}" -e 0,50,50,800,800
-  #wmctrl ${iopt} -r "${idOrTitle}" -b add,maximized_vert,maximized_horz
+  
+  # wmctrl "${iopt}" -r "${idOrTitle}" -b remove,maximized_vert,maximized_horz
+  # wmctrl "${iopt}" -r "${idOrTitle}" -b remove,maximized_vert,maximized_horz
 }
 
 # ======= ! CONFIGURATIONS ==============
@@ -39,20 +44,19 @@ printHelpMessage() {
 
 echo -ne "\
 Usage:
-  exeprogandwindact [options] -- <command> <window class> <delay time(sec)>
+  exeprogandwindact [options] -- <command> <window class> <delay time (sec)>
 
   command:            command to run
-  window class:       class of the window that is opened by the
-                      command (only used to check if the window
-                      is already open; no action will be taken
-                      if so)
-  delay time(sec):    time required for the window to open before
-                      moving it (min: .1; max: 25)
+  window class:       class of the window that is opened by the command
+                      (only used to check if the window is already open;
+                      no action will be taken if so)
+  delay time (sec):   time required to wait for the window to open (min:
+                      .1; max: 25)
 
 Options:
   -t --title <TITLE>  specify the window title to use instead of the class
-  -g --geometry       geometry to use for positioning the window (instead of
-                      using the window action); format: X,Y,WIDTH,HEIGHT
+  -g --geometry       geometry to use for positioning the window (will
+                      ignore the window action); format: X,Y,WIDTH,HEIGHT
   --pre-execute       command to pre-execute (sometimes needed, e.g., when
                       having to cd to a directory first)
   -h --help           help message
@@ -98,18 +102,18 @@ else
   # arguments.
   COMMAND="${@:1:$(($#-2))}"
   WIND_CLASS="${@: -2:1}"
-  DELAY_TIME_BFR_MOVE="${@: -1:1}"
+  DELAY_TIME_BFR_RUNNING_ACT="${@: -1:1}"
 fi
 
-if [[ ${DELAY_TIME_BFR_MOVE} =~ ('.'*)([0-9]*) ]]; then
-  if [[ -z ${BASH_REMATCH[1]} && ${BASH_REMATCH[2]} -gt 25 ]]; then
-    echo -e 'exeprogandwindact: delay time invalid: should not\n  be greater than'\
-        '25' 1>&2
+if [[ "${DELAY_TIME_BFR_RUNNING_ACT}" =~ ('.'*)([0-9]*) ]]; then
+  if [[ -z "${BASH_REMATCH[1]}" && "${BASH_REMATCH[2]}" -gt 25 ]]; then
+    echo -e 'exeprogandwindact: delay time invalid: should not\n  be greater'\
+        'than 25' 1>&2
     exit 1
   fi
 else
-  echo -e 'exeprogandwindact: delay time invalid: leading decimal\n  and numbers'\
-      'allowed only' 1>&2
+  echo -e 'exeprogandwindact: delay time invalid: leading decimal\n  and'\
+      'numbers allowed only' 1>&2
   exit 1
 fi
 
@@ -117,16 +121,17 @@ fi
 #   Utilitiy functions
 # ============================================
 
-isWindOpen() {
-  CLASS_WIND_IDS=($(wmctrl -lx | awk -v class="${1}" '$3 ~ class {print $1}'))
-  [[ "${#CLASS_WIND_IDS[@]}" -gt 0 ]] && return 0 || return 1
+isWindOpenByClass() {
+  local classWindIds=($(wmctrl -lx | awk -v class="${1}" '$3 ~ class \
+      {print $1}'))
+  [[ "${#classWindIds[@]}" -gt 0 ]] && return 0 || return 1
 }
 
 getWindIdByPid() {
   while IFS= read line; do
     if [[ "${line}" =~ (0x)([0-9a-z]+)([ ][- ][0-9]+[ ])([0-9]*) ]]; then
-      winId="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
-      pid="${BASH_REMATCH[4]}"
+      local winId="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
+      local pid="${BASH_REMATCH[4]}"
       if [ "${pid}" -eq "${1}" ]; then
         echo "${winId}"
         break
@@ -139,21 +144,15 @@ getWindIdByPid() {
 #   Run the program
 # ============================================
 
-if isWindOpen "${WIND_CLASS}"; then
-  ALREADY_OPENED=true
-fi
-
 if [ -n "${PRE_EXEC_CMD}" ]; then
   ${PRE_EXEC_CMD} # do not quote
 fi
 
-# Do not quote ${COMMAND} because if the command's arguments contain newlines,
-# the text on each new line will be interpreted as an individual command.
-eval ${COMMAND}
+eval "(${COMMAND}) &"
 PID=$!
 
-if [[ -n "${PID}" && ! "${ALREADY_OPENED}" = true ]]; then
-  sleep "${DELAY_TIME_BFR_MOVE}"
+if [ -n "${PID}" ] && ! isWindOpenByClass "${WIND_CLASS}"; then
+  sleep "${DELAY_TIME_BFR_RUNNING_ACT}"
 
   [ -z "${WIND_TITLE}" ] && windId="$(getWindIdByPid "${PID}")"
 
@@ -161,7 +160,7 @@ if [[ -n "${PID}" && ! "${ALREADY_OPENED}" = true ]]; then
     if [ -n "${GEOMETRY}" ]; then
       { [ -z "${WIND_TITLE}" ] && idOrTitle="${windId}" && iopt='-i'; } || \
           idOrTitle="${WIND_TITLE}"
-      wmctrl ${iopt} -r "${idOrTitle}" -e "0,${GEOMETRY}" &
+      wmctrl "${iopt}" -r "${idOrTitle}" -e "0,${GEOMETRY}" &
     else
       WIND_ACTION "${windId}" &
     fi
