Rename and update description for returnfileforcmd

diff --git a/scripts/linux-modules/file_management/returnfilesforcmd b/scripts/linux-modules/file_management/returnfilesforcmd
--- a/scripts/linux-modules/file_management/returnfilesforcmd
+++ b/scripts/linux-modules/file_management/returnfilesforcmd
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 # 
-# Return a file for a command using one of two search methods: (1) Locate from a
-# database; (2) Recursively find from the current or specified directory.
+# Return one or more files for a command using one of two search methods: (1)
+# Locate from a database; (2) Recursively find from the current or specified
+# directory.
 # 
 # Options are provided to find files or directories only and change the find
 # occurrence for both methods. An option is provided to return all occurrences
@@ -9,13 +10,13 @@
 # 
 # Examples:
 #   # locate a file from a database for gedit
-#   alias geditloc='returnfileforcmd {gedit --new-window} --l'
+#   alias geditloc='returnfilesforcmd {gedit --new-window} --l'
 # 
 #   # recursively find a file from the current or specified directory for gedit
-#   alias geditr='returnfileforcmd {gedit --new-window} --r'
+#   alias geditr='returnfilesforcmd {gedit --new-window} --r'
 # 
 #   # same as previous except allow files only to be returned
-#   alias geditr='returnfileforcmd {gedit --new-window} --r --f'
+#   alias geditr='returnfilesforcmd {gedit --new-window} --r --f'
 # 
 #   # use the aliases on their own or with other options such as --3 to return
 #   # the third found occurrence or --a to return all occurrences.
@@ -23,7 +24,7 @@
 #   geditr --a config.sh
 # 
 # Usage:
-#   returnfileforcmd {<command to execute>} [options] <partial file name>
+#   returnfilesforcmd {<command to execute>} [options] <partial file name>
 #         [directory]
 # 
 #   directory: directory to search in; applies only to the recursive search
@@ -82,7 +83,7 @@ for ((x=1; x<=$#; x++)); do
   fi
 done
 if [ -z "${execCmd}" ]; then
-  echo -e  'returnfileforcmd: invalid arguments:\nexecute command not'\
+  echo -e  'returnfilesforcmd: invalid arguments:\nexecute command not'\
       'specified' 1>&2
   exit 1
 fi
@@ -91,7 +92,7 @@ execCmd="${execCmd#{}"
 execCmd="${execCmd%\}}"
 
 OPTS="$(getopt -q -o '#' --long l,r,f,d,1,2,3,4,5,6,7,8,9,a,e -n \
-    'returnfileforcmd' -- "${@}")"
+    'returnfilesforcmd' -- "${@}")"
 eval set -- "${OPTS}"
 while true; do
   case "${1}" in
@@ -111,11 +112,11 @@ done
 case "${SEARCH_METHOD}" in
   'locate')
     if [ "$#" -eq 0 ]; then
-      echo 'returnfileforcmd: no file specified' 1>&2
+      echo 'returnfilesforcmd: no file specified' 1>&2
       exit 1
     fi
     if ! hash ${LOCATE_COMMAND} > /dev/null 2>&1; then
-      echo "returnfileforcmd: command \"${LOCATE_COMMAND}\" does not"\
+      echo "returnfilesforcmd: command \"${LOCATE_COMMAND}\" does not"\
           "exist" 1>&2
       exit 1
     fi
@@ -133,7 +134,7 @@ case "${SEARCH_METHOD}" in
     output="$(${LOCATE_COMMAND} ${lctOpts} "${@}")"
 
     if [ -z "${output}" ]; then
-      echo 'returnfileforcmd: no files or directories found' 1>&2
+      echo 'returnfilesforcmd: no files or directories found' 1>&2
     else
       output="$(echo "${output}" | sed 's/ /\\n/g')"
 
@@ -147,7 +148,7 @@ case "${SEARCH_METHOD}" in
 
   'recursively find')
     if [ "$#" -eq 0 ]; then
-      echo 'returnfileforcmd: no file specified' 1>&2
+      echo 'returnfilesforcmd: no file specified' 1>&2
       exit 1
     elif [ "$#" -ge 2 ]; then
       dir="${2}"
@@ -162,7 +163,7 @@ case "${SEARCH_METHOD}" in
     output="$(find "${dir}" ${optType} -name "*${1}*" 2>/dev/null)"
 
     if [ -z "${output}" ]; then
-      echo 'returnfileforcmd: no files or directories found' 1>&2
+      echo 'returnfilesforcmd: no files or directories found' 1>&2
     else
       if [ "${ALL_OCCURRENCES}" != 'true' ]; then
         if [ -n "${FIND_OCCURRENCE}" ]; then
