mongodbutil update

diff --git a/bin/3rd_party_applications/database/mongodbutil b/bin/3rd_party_applications/database/mongodbutil
--- a/bin/3rd_party_applications/database/mongodbutil
+++ b/bin/3rd_party_applications/database/mongodbutil
@@ -3,79 +3,98 @@
 # Generic utility functions for MongoDB.
 # 
 # Usage:
-#   mongodbutil <action> [action arguments]
+#   mongodbutil <database name> <action> [action arguments]
 # 
 
-readonly ACTION="${1}"
-readonly DB_NAME="${2}"
-
-if [ "$#" -lt 1 ]; then
-  echo "mongodbutil: no action specified" 1>&2
+if [ "$#" -lt 2 ]; then
+  echo -e  'mongodbutil: invalid number of arguments; database name\n  and' \
+      'action required' 1>&2
   exit 1
 fi
 
-shift
-
-dbNotSpecified() {
-  if [ -z "${DB_NAME}" ]; then
-    echo "mongodbutil: no database specified" 1>&2
-    return 1
-  fi
-}
+readonly DB_NAME="${1}"
+readonly ACTION="${2}"
+shift 2
 
 case "${ACTION}" in
-  # Import data from JSON file
-  # Arguments:
-  #   1. JSON file name
-  #   2. (Optional) Name for the collection; default is JSON file name
+  # Export data to JSON file.
+  # 
+  # Usage:
+  #   ... export <collection name> [out directory]
+  # 
+  #   collection name:     also used as the name for the JSON file.
+  #   out directory:       default is current.
+  'export')
+    if [ "$#" -ge 1 ]; then
+      collName="${1}"
+      opts+="--collection ${collName}"
+
+      if [ "$#" -ge 2 ]; then
+        opts+=" --out ${2}/${collName}.json"
+      else
+        opts+=" --out ${collName}.json"
+      fi
+    fi
+
+    mongoexport --db "${DB_NAME}" ${opts} --jsonArray
+    ;;
+
+  # Import data from JSON file.
+  # 
+  # Usage:
+  #   ... import <JSON file name> [collection name]
+  # 
+  #   collection name:     default is JSON file name.
+  # 
+  # Note:
+  #   If needing to import multiple MongoDB documents within a single JSON
+  #   array, use the "--jsonArray" option at the end of mongoimport.
   'import')
-    if dbNotSpecified; then exit 1; else shift; fi
-    if [ "$#" -lt 1 ]; then
+    if [ "$#" -eq 0 ]; then
       echo "mongodbutil: no directory specified" 1>&2
       exit 1
-    elif [ ! -f "${1}" ]; then
+    fi
+    if [ ! -f "${1}" ]; then
       echo "mongodbutil: cannot import: file \"${1}\" does not exist" 1>&2
       exit 1
     fi
 
-    if [ -n "${2}" ]; then
-      addtOpts+="--collection ${2}"
+    if [ "$#" -ge 2 ]; then
+      opts+="--collection ${2}"
     fi
 
-    mongoimport --db "${DB_NAME}" --file "${1}" ${addtOpts} --jsonArray
+    mongoimport --db "${DB_NAME}" --file "${1}" ${opts}
     ;;
 
-  # Export data to JSON file
-  # Arguments:
-  #   1. Collection name (also used as the name for the JSON file)
-  #   2. (Optional) Directory where JSON file should be saved; default is
-  #      current
-  'export')
-    if dbNotSpecified; then exit 1; else shift; fi
+  # Dump database (outputs BSON files in contrast to export which outputs JSON
+  # files).
+  # 
+  # Usage:
+  #   ... dump [collection name] [out directory]
+  # 
+  #   collection name:     default is all.
+  'dump')
+    if [ "$#" -ge 1 ]; then
+      opts+="--collection ${1}"
 
-    if [ -n "${1}" ]; then
-      collName="${1}"
-      addtOpts+="--collection ${collName}"
-    fi
-    if [ -n "${2}" ]; then
-      addtOpts+=" --out ${2}/${collName}.json"
-    else
-      addtOpts+=" --out ${collName}.json"
+      if [ "$#" -ge 2 ]; then
+        opts=" --out ${2}"
+      fi
     fi
 
-    mongoexport --db "${DB_NAME}" ${addtOpts}
+    mongodump --db "${DB_NAME}" ${opts}
     ;;
 
-  # Restore data from BSON files generated with mongodump
-  # Arguments:
-  #   1. Directory or file containing the exported data
+  # Restore data from BSON files.
+  # 
+  # Usage:
+  #   ... restore <file or directory containing exported data>
   'restore')
-    if dbNotSpecified; then exit 1; else shift; fi
-
     if [ -z "${1}" ]; then
       echo "mongodbutil: no directory specified"  1>&2
       exit 1
-    elif [ ! -d "${1}" ]; then
+    fi
+    if [ ! -d "${1}" ]; then
       echo "mongodbutil: directory \"${1}\" does not exist"  1>&2
       exit 1
     fi
@@ -83,55 +102,40 @@ case "${ACTION}" in
     mongorestore "${1}"
     ;;
 
-  # Dump database (uses BSON files in contrast to export which uses JSON)
-  # Arguments:
-	#   1. (Optional) Directory where mongodump will write the BSON files;
-	#      default is current
-  #   2. (Optional) Database collection to dump; default is all
-  'dump')
-    if dbNotSpecified; then exit 1; else shift; fi
-
-    if [ -n "${1}" ]; then
-      addtOpts="--out ${1}"
-    fi
-    if [ -n "${2}" ]; then
-      addtOpts+=" --collection ${2}"
-    fi
-
-    mongodump --db "${DB_NAME}" ${addtOpts}
-    ;;
-
-  # Drop a database
-  # Arguments:
-  #   1. Database name
+  # Drop the database.
+  # 
+  # Usage:
+  #   ... drop
   'drop')
-    if dbNotSpecified; then exit 1; else shift; fi
-
     mongo "${DB_NAME}" --eval 'db.dropDatabase()'
     ;;
 
-  # Drop all databases
-  'dropall')
-		/usr/bin/mongo <<-EOF
+  # Drop all databases.
+  # 
+  # Usage:
+  #   ... drop_all
+  'drop_all')
+    /usr/bin/mongo <<-EOF
 			db.getMongo().getDBNames().forEach(function(database) {
-					if (database != 'local' && database != 'admin') {
-						db = db.getMongo().getDB(database);
-						db.dropDatabase();
-						print('dropped database ' + db.getName());
-					}
-				})
+				if (database != 'local' && database != 'admin') {
+					db = db.getMongo().getDB(database);
+					db.dropDatabase();
+					print('dropped database ' + db.getName());
+				}
+			})
 		EOF
     ;;
 
-  # Prints info for all databases
-  # Arguments:
-	#   1. (Optional) Database name; default is all
+  # Print general information for the database.
+  # 
+  # Usage:
+  #   ... info
+  # 
+  # Note:
+  #   Information for all databases can be printed simultaneously if DB_NAME
+  #   is empty.
   'info')
-    if [ -n "${1}" ]; then
-      dbName="${1}"
-    fi
-
-		/usr/bin/mongo --eval "var param1='${dbName}'" --shell <<-EOF
+    /usr/bin/mongo --eval "var param1='${DB_NAME}'" --shell <<-EOF
 			db = db.getSiblingDB('admin');
 			dbs = db.getMongo().getDBNames();
 
@@ -162,15 +166,14 @@ esac
 
 
 
-
-
-
-
-
-# DOCUMENTATION
+# 
 # ================================================
-# ~~The following link provides a table that maps the most common mongo shell
-#   helpers to their JavaScript equivalents which can be used
-#   outside the mongo shell.
+#   REFERENCES
+# ================================================
+# 
+# The following link provides a table that maps the most common mongo shell
+# helpers to their JavaScript equivalents:
+# 
 # https://docs.mongodb.org/manual/tutorial/write-scripts-for-the-mongo-shell/#differences-between-interactive-and-scripted-mongo
+# 
 
