Update mtp

diff --git a/bin/mobile/mtp b/bin/mobile/mtp
--- a/bin/mobile/mtp
+++ b/bin/mobile/mtp
@@ -31,6 +31,11 @@ DEV_CD_DIR='Internal storage/DCIM/Camera'
 # ======= ! CONFIGURATIONS ==============
 
 mtp() {
+	if [ "$#" -eq 0 ]; then
+		echo 'mtp: no arguments: "mount", "m", "unmount" or "u" required' 1>&2
+		return 1
+	fi
+
   case "${1}" in
     'mount'|'m')
       if [ ! -d "${MOUNTPOINT_DIR}" ]; then
@@ -39,7 +44,9 @@ mtp() {
 
       if ! mount | grep "${MOUNTPOINT_DIR}" >/dev/null; then
         jmtpfs "${MOUNTPOINT_DIR}"
-        cd "${MOUNTPOINT_DIR}/${DEV_CD_DIR}"
+        if mount | grep "${MOUNTPOINT_DIR}" >/dev/null; then
+	        cd "${MOUNTPOINT_DIR}/${DEV_CD_DIR}"
+	      fi
       fi
       ;;
       
@@ -49,7 +56,7 @@ mtp() {
       fi
 
       fusermount -u "${MOUNTPOINT_DIR}"
-      if ! mount | grep "${MOUNTPOINT_DIR}" >/dev/null; then
+      if [ "$?" -eq 0 ] && ! mount | grep "${MOUNTPOINT_DIR}" >/dev/null; then
         echo "mtp: device successfully unmounted from ${MOUNTPOINT_DIR}"
       fi
       ;;
