file name execmdandwindact changed to exeprogandwindact

diff --git a/bin/modules/x11/exeprogandwindact b/bin/modules/x11/exeprogandwindact
--- a/bin/modules/x11/exeprogandwindact
+++ b/bin/modules/x11/exeprogandwindact
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # 
-# Execute a command and an action on the resulting window.
+# Execute a program and an action on the resulting window.
 # 
 # Dependencies:
 #   wmctrl (used to determine if the window is already open and get the window
@@ -39,7 +39,7 @@ printHelpMessage() {
 
 echo -ne "\
 Usage:
-  execmdandwindact [options] -- <command> <window class> <delay time(sec)>
+  exeprogandwindact [options] -- <command> <window class> <delay time(sec)>
 
   command:            command to run
   window class:       class of the window that is opened by the
@@ -60,7 +60,7 @@ Options:
 }
 
 OPTS="$(getopt -o t:,g:,h --long title:,geometry:,pre-execute:,help -n \
-    'execmdandwindact' -- "${@}")"
+    'exeprogandwindact' -- "${@}")"
 [ "$?" -ne 0 ] && echo "exiting..." 1>&2 && exit 1
 eval set -- "${OPTS}"
 while true; do
@@ -68,7 +68,7 @@ while true; do
     --title|-t) WIND_TITLE="${2}"; shift;;
     --geometry|-g)
       if [[ ! "${2}" =~ [0-9]*,[0-9]*,[0-9]*,[0-9] ]]; then
-        echo -e 'execmdandwindact: geometry not in correct format' 1>&2
+        echo -e 'exeprogandwindact: geometry not in correct format' 1>&2
         printHelpMessage
         exit 1
       else
@@ -84,17 +84,18 @@ while true; do
 done
 
 if [ "$#" -eq 0 ]; then
-  echo -e 'execmdandwindact: no arguments' 1>&2
+  echo -e 'exeprogandwindact: no arguments' 1>&2
   printHelpMessage
   exit 1
 elif [ "$#" -lt 3 ]; then
-  echo -e 'execmdandwindact: invalid number of arguments' 1>&2
+  echo -e 'exeprogandwindact: invalid number of arguments' 1>&2
   printHelpMessage
   exit 1
 else
   # must get all arguments before last two because if the command contains
   # "${@}" (e.g. exeandmo.. "/usr/bin/chromium ${@}" <class> [..]), then the
-  # command and the arguments in "${@}"  will be interpreted as separate arguments.
+  # command and the arguments in "${@}"  will be interpreted as separate
+  # arguments.
   COMMAND="${@:1:$(($#-2))}"
   WIND_CLASS="${@: -2:1}"
   DELAY_TIME_BFR_MOVE="${@: -1:1}"
@@ -102,15 +103,19 @@ fi
 
 if [[ ${DELAY_TIME_BFR_MOVE} =~ ('.'*)([0-9]*) ]]; then
   if [[ -z ${BASH_REMATCH[1]} && ${BASH_REMATCH[2]} -gt 25 ]]; then
-    echo -e 'execmdandwindact: delay time invalid: should not\n  be greater than'\
+    echo -e 'exeprogandwindact: delay time invalid: should not\n  be greater than'\
         '25' 1>&2
     exit 1
   fi
 else
-  echo -e 'execmdandwindact: delay time invalid: leading decimal\n  and numbers'\
+  echo -e 'exeprogandwindact: delay time invalid: leading decimal\n  and numbers'\
       'allowed only' 1>&2
   exit 1
 fi
+
+# ============================================
+#   Utilitiy functions
+# ============================================
 
 isWindOpen() {
   CLASS_WIND_IDS=($(wmctrl -lx | awk -v class="${1}" '$3 ~ class {print $1}'))
@@ -129,6 +134,10 @@ getWindIdByPid() {
     fi
   done < <(wmctrl -lp)
 }
+
+# ============================================
+#   Run the program
+# ============================================
 
 if isWindOpen "${WIND_CLASS}"; then
   ALREADY_OPENED=true
