Rename mysqlutil and mongodbutil

diff --git a/functions_scripts/applications/databases/mongodbutils b/functions_scripts/applications/databases/mongodbutils
--- a/functions_scripts/applications/databases/mongodbutils
+++ b/functions_scripts/applications/databases/mongodbutils
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 # 
-# Generic NoSQL database functions for MongoDB
+# NoSQL functions for MongoDB
 # 
 # Usage:
-#   mongodbutil <database name> <action> [action arguments]
+#   mongodbutils <database name> <action> [action arguments]
 # 
 
 if [ "$#" -lt 2 ]; then
-  echo -e  'mongodbutil: invalid number of arguments; database name\n  and' \
+  echo -e  'mongodbutils: invalid number of arguments; database name\n  and' \
       'action required' 1>&2
   exit 1
 fi
@@ -49,11 +49,11 @@ case "${ACTION}" in
   #   array, use the "--jsonArray" option at the end of mongoimport.
   'import')
     if [ "$#" -eq 0 ]; then
-      echo "mongodbutil: no directory specified" 1>&2
+      echo "mongodbutils: no directory specified" 1>&2
       exit 1
     fi
     if [ ! -f "${1}" ]; then
-      echo "mongodbutil: cannot import: file \"${1}\" does not exist" 1>&2
+      echo "mongodbutils: cannot import: file \"${1}\" does not exist" 1>&2
       exit 1
     fi
 
@@ -87,11 +87,11 @@ case "${ACTION}" in
   #   ... restore <file or directory containing exported data>
   'restore')
     if [ -z "${1}" ]; then
-      echo "mongodbutil: no directory specified"  1>&2
+      echo "mongodbutils: no directory specified"  1>&2
       exit 1
     fi
     if [ ! -d "${1}" ]; then
-      echo "mongodbutil: directory \"${1}\" does not exist"  1>&2
+      echo "mongodbutils: directory \"${1}\" does not exist"  1>&2
       exit 1
     fi
 
@@ -121,7 +121,7 @@ case "${ACTION}" in
     ;;
 
   *)
-    echo "mongodbutil: unknown action \"${ACTION}\"" 1>&2
+    echo "mongodbutils: unknown action \"${ACTION}\"" 1>&2
     exit 1
     ;;
 
diff --git a/functions_scripts/applications/databases/mysqlutils b/functions_scripts/applications/databases/mysqlutils
--- a/functions_scripts/applications/databases/mysqlutils
+++ b/functions_scripts/applications/databases/mysqlutils
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 # 
-# Generic RDBMS functions for MySQL
+# RDBMS functions for MySQL
 # 
 # Usage:
-#   mysqlutil <databaes user> <database name> <action>
+#   mysqlutils <databaes user> <database name> <action>
 # 
 
 if [ "$#" -lt 3 ]; then
-  echo -e  'mysqlutil: invalid number of arguments; database user,\n' \
+  echo -e  'mysqlutils: invalid number of arguments; database user,\n' \
       '  database name and action required' 1>&2
   exit 1
 fi
@@ -23,11 +23,11 @@ case "${ACTION}" in
   #   ... create <create SQL file>
   'create')
     if [ "$#" -eq 0 ]; then
-      echo "mysqlutil: no SQL file specified" 1>&2
+      echo "mysqlutils: no SQL file specified" 1>&2
       exit 1
     fi
     if [ ! -f "${1}" ]; then
-      echo "mysqlutil: file \"${1}\" not found" 1>&2
+      echo "mysqlutils: file \"${1}\" not found" 1>&2
       exit 1
     fi
 
@@ -37,7 +37,7 @@ case "${ACTION}" in
       bash ${0} 'droptables' "${DB_USER}" "${DB_NAME}"
       mysql -u"${DB_USER}" "${DB_NAME}" < "${1}"
     else
-      echo "mysqlutil: database \"${DB_NAME}\" not found" 1>&2
+      echo "mysqlutils: database \"${DB_NAME}\" not found" 1>&2
     fi
     ;;
     
@@ -82,7 +82,7 @@ case "${ACTION}" in
     ;;
     
   *)
-    echo "mysqlutil: unknown action \"${ACTION}\"" 1>&2
+    echo "mysqlutils: unknown action \"${ACTION}\"" 1>&2
     ;;
 
 esac
