Update script name and description in remvlastnentriesfrombashhist

diff --git a/scripts/shell_management/history_management/remvlastnentriesfrombashhist b/scripts/shell_management/history_management/remvlastnentriesfrombashhist
--- a/scripts/shell_management/history_management/remvlastnentriesfrombashhist
+++ b/scripts/shell_management/history_management/remvlastnentriesfrombashhist
@@ -1,26 +1,26 @@
 #!/usr/bin/env bash
 # 
 # File:
-#   remlastnbashhistentries
+#   remvlastnentriesfrombashhist
 # 
 # Description:
-#   Remove the last N bash history entries.
+#   Remove the last N entries from the bash history.
 # 
 # Usage (script must be sourced for history command to work):
-#   source remlastnbashhistentries; _remlastnbashhistentries <1-100>
+#   source remvlastnentriesfrombashhist; _remvlastnentriesfrombashhist <1-100>
 # 
 # Source:
 #   http://unix.stackexchange.com/a/65076
 # 
 
-_remlastnbashhistentries() {
+_remvlastnentriesfrombashhist() {
   local numCurrHistEntries="$(history | wc -l)"
 
   if [ "$#" -eq 0 ]; then
-    echo -e 'remlastnbashhistentries: no argument' 1>&2
+    echo -e 'remvlastnentriesfrombashhist: no argument' 1>&2
     return 1
   elif [[ ! "${1}" =~ ^[0-9]+$ || "${1}" -lt 1 || "${1}" -gt 100 ]]; then
-    echo -e 'remlastnbashhistentries: invalid argument; must be a number\n'\
+    echo -e 'remvlastnentriesfrombashhist: invalid argument; must be a number\n'\
         ' between 1 and 100 (inclusive)' 1>&2
     return 1
   fi
