Update documentation and argument error exit codes in linux-output_only-single-value/x11/

diff --git a/scripts/linux-output_only-single-value/x11/iswindopen b/scripts/linux-output_only-single-value/x11/iswindopen
--- a/scripts/linux-output_only-single-value/x11/iswindopen
+++ b/scripts/linux-output_only-single-value/x11/iswindopen
@@ -12,9 +12,14 @@
 #         class can be specified using the full qualified class string [i.e.
 #         class and classname; e.g. "xterm.XTerm"]; does not allow regex)
 # 
+# Exit codes:
+#   0: window is open
+#   1: window is not open
+#   2: no arguments error
+# 
 
 if [ "$#" -eq 0 ]; then
-  exit 1
+  exit 2
 fi
 
 while getopts :c OPT; do
